'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ResMon.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cc_moon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cc_moon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cc_moon_clouds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cc_moon_clouds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cc_moon_lighting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cc_moon_lighting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cc_moon_rain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cc_moon_rain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cc_NA_clouds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cc_NA_clouds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cc_NA_lighting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cc_NA_lighting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cc_NA_rain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cc_NA_rain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cc_sun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cc_sun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cc_sun_clouds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cc_sun_clouds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cc_sun_lighting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cc_sun_lighting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cc_sun_rain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cc_sun_rain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property diagnostic_chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diagnostic_chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property http_status_ok_success() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("http_status_ok_success", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images_flickr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images_flickr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_cloud_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_cloud_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_cloud_moon_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_cloud_moon_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_cloud_moon_rain_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_cloud_moon_rain_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_cloud_rain_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_cloud_rain_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_cloud_sun_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_cloud_sun_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_cloud_wind_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_cloud_wind_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_cloudy_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_cloudy_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_moon_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_moon_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_sun_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_sun_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_sun_windy_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_sun_windy_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_thunder_wind_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_thunder_wind_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_thunderstorm_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_thunderstorm_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_thunderstorm_rain_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_thunderstorm_rain_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_wind_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_wind_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_wind_moon_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_wind_moon_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kk_wind_rain_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kk_wind_rain_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property progressbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("progressbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_list_bullets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_list_bullets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This application uses some parts which provided by third party.
        '''
        '''Microsoft Edge WebView2
        '''© Microsoft Corporation
        '''
        '''Network Monitor
        '''© Chen Pang &quot;Echevil&quot;
        '''
        '''Json.NET
        '''© Newtonsoft
        '''
        '''Open Hardware Monitor
        '''© Michael Möller
        '''
        '''Dynamically Resize and Reposition All Controls
        '''© Member 10974085
        '''
        '''Simple Performance Chart
        '''© eclipse2k1
        '''
        '''Weather API
        '''© Malaysian Meteorological Department
        '''
        '''MaterialSkin 2 for .NET WinForms
        '''© leocb &amp; orapps44.
        '''</summary>
        Friend ReadOnly Property ThirdParty() As String
            Get
                Return ResourceManager.GetString("ThirdParty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weather_sun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weather_sun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property youtube() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youtube", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
